app/auth.py
from flask import Blueprint, render_template, request, session, redirect, url_for
from passlib.hash import sha256_crypt
from .db import execute_query

auth_routes = Blueprint('auth', __name__)

@auth_routes.route('/')
def index():
    return render_template('login.html')

@auth_routes.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        input_username = request.form['username']
        input_password = request.form['password']

        check_user_query = "SELECT username, password, role FROM users WHERE username = %s"
        user_data = execute_query(check_user_query, (input_username,))

        stored_username = None

        if user_data:
            stored_username, stored_password, role = user_data[0]

        if input_username == stored_username and sha256_crypt.verify(input_password, stored_password):
            # Store the user's role in the session
            session['role'] = role
            session['logged_in'] = True
            return redirect(url_for('main.dashboard'))

    return render_template('login.html')

@auth_routes.route('/logout')
def logout():
    session.clear()
    if 'timeout' in request.args:
        return render_template('timeout.html')
    return redirect(url_for('auth.index'))

app/routes.py
from flask import Blueprint, session, redirect, url_for, render_template, jsonify, request, Response
from .utils import get_all_categories, column_mapping, get_category_data
from .db import execute_query

main_routes = Blueprint('main', __name__)

@main_routes.route('/dashboard')
def dashboard():
    if not session.get('logged_in'):
        return redirect(url_for('auth.login'))

    categories = get_all_categories()

    total_count_query = "SELECT SUM(cnt) FROM ("
    for category in categories:
        total_count_query += f"SELECT COUNT(*) as cnt FROM {category} UNION ALL "
    total_count_query = total_count_query[:-10] + ") as total"
    total_count_result = execute_query(total_count_query)
    total_count = total_count_result[0][0] if total_count_result else 0

    if session['role'] == 'admin':
        return render_template('dashboard.html', categories=categories, column_mapping=column_mapping, total_count=total_count, is_admin=True)
    else:
        return render_template('dashboard.html', categories=categories, column_mapping=column_mapping, total_count=total_count, is_admin=False)


@main_routes.route('/get_columns/<category>')
def get_columns_endpoint(category):
    columns, _ = get_category_data(category)
    return jsonify({'columns': columns})
    return columns, devices


@main_routes.route('/get_total_count_data')
def get_total_count_data():
    tables_query = "SHOW TABLES"
    tables_result = execute_query(tables_query)
    tables = [table[0] for table in tables_result if table[0] != 'users']

    table_counts = []

    for table in tables:
        count_query = f"SELECT COUNT(*) FROM {table}"
        count_result = execute_query(count_query)
        count = count_result[0][0]
        table_counts.append((column_mapping.get(table, table), table, count))

    labels_mapped, labels_original, counts = zip(*table_counts)

    return jsonify({'labels_mapped': labels_mapped, 'labels_original': labels_original, 'values': counts})


@main_routes.route('/segmentation/<category>')
def segmentation(category):
    if not session.get('logged_in'):
        return redirect(url_for('auth.login'))

    columns, devices = get_category_data(category)

    if session['role'] == 'admin':
        return render_template('segmentation.html', category=category, column_mapping=column_mapping, columns=columns,
                               devices=devices, is_admin=True, table_name=column_mapping.get(category, category))
    else:
        return render_template('segmentation.html', category=category, column_mapping=column_mapping, columns=columns,
                               devices=devices, is_admin=False, table_name=column_mapping.get(category, category))


@main_routes.route('/add_device', methods=['POST'])
def add_device():
    if not session.get('logged_in') or session['role'] != 'admin':
        return redirect(url_for('login'))

    if request.method == 'POST':
        currentCategory = request.form.get('category')

        columns, _ = get_category_data(currentCategory)

        values = [request.form.get(column) for column in columns]

        insert_query = f"INSERT INTO {currentCategory} ({', '.join(columns)}) VALUES ({', '.join(['%s'] * len(columns))})"

        insert = execute_query(insert_query, values, operation="insert")

        if insert:
            return redirect(url_for('main.segmentation', category=currentCategory))
        else:
            return "Failed to add the device. Please try again."

    return render_template('segmentation.html')


@main_routes.route('/update_device', methods=['POST'])
def update_device():
    try:
        data = request.get_json()

        category = data.get('category')
        primary_key = data.get('id')

        # Ensure category and identifier are provided
        if not category or not primary_key:
            return jsonify({'success': False, 'error': 'Category and primary key are required'})

        updated_data = {key: data.get(key) for key in data.keys() if key not in {'id', 'category'}}

        if not updated_data:
            return jsonify({'success': False, 'error': 'No fields to update'})

        if category == 'person':
            set_clause = ', '.join([f"{key} = %s" for key in updated_data.keys()])
            update_query = f"UPDATE person SET {set_clause} WHERE ssn = %s"
            update_data = list(updated_data.values()) + [primary_key]

        elif category == 'library_member':
            set_clause = ', '.join([f"{key} = %s" for key in updated_data.keys()])
            update_query = f"UPDATE library_member SET {set_clause} WHERE member_id = %s"
            update_data = list(updated_data.values()) + [primary_key]

        elif category == 'subject_area':
            set_clause = ', '.join([f"{key} = %s" for key in updated_data.keys()])
            update_query = f"UPDATE subject_area SET {set_clause} WHERE subject_name = %s"
            update_data = list(updated_data.values()) + [primary_key]

        elif category == 'book':
            set_clause = ', '.join([f"{key} = %s" for key in updated_data.keys()])
            update_query = f"UPDATE book SET {set_clause} WHERE isbn = %s"
            update_data = list(updated_data.values()) + [primary_key]

        elif category == 'volume':
            set_clause = ', '.join([f"{key} = %s" for key in updated_data.keys()])
            update_query = f"UPDATE volume SET {set_clause} WHERE barcode_number = %s"
            update_data = list(updated_data.values()) + [primary_key]

        elif category == 'book_loan':
            set_clause = ', '.join([f"{key} = %s" for key in updated_data.keys()])
            update_query = f"UPDATE book_loan SET {set_clause} WHERE loan_id = %s"
            update_data = list(updated_data.values()) + [primary_key]

        else:
            return jsonify({'success': False, 'error': 'Invalid category provided'})

        update = execute_query(update_query, update_data, "update")

        if update:
            return jsonify({'success': True, 'message': f'{category.capitalize()} updated successfully'})
        else:
            return jsonify({'success': False, 'error': f'Failed to update {category}'})

    except Exception as e:
        print('Exception:', str(e))
        return jsonify({'success': False, 'error': 'Invalid data format'})


@main_routes.route('/delete_device', methods=['POST'])
def delete_device():
    try:
        data = request.get_json()

        category = data.get('category')
        primary_key = data.get('id')

        if not category or not primary_key:
            return jsonify({'success': False, 'error': 'Category and primary key are required'})

        if category == 'person':
            delete_query = f"DELETE FROM person WHERE ssn = %s"
            delete_data = (primary_key,)

        elif category == 'library_member':
            delete_query = f"DELETE FROM library_member WHERE member_id = %s"
            delete_data = (primary_key,)

        elif category == 'subject_area':
            delete_query = f"DELETE FROM subject_area WHERE subject_name = %s"
            delete_data = (primary_key,)

        elif category == 'book':
            delete_query = f"DELETE FROM book WHERE isbn = %s"
            delete_data = (primary_key,)

        elif category == 'volume':
            delete_query = f"DELETE FROM volume WHERE barcode_number = %s"
            delete_data = (primary_key,)

        elif category == 'book_loan':
            delete_query = f"DELETE FROM book_loan WHERE loan_id = %s"
            delete_data = (primary_key,)

        else:
            return jsonify({'success': False, 'error': 'Invalid category provided'})

        delete = execute_query(delete_query, delete_data, "delete")

        if delete:
            return jsonify({'success': True, 'message': f'{category.capitalize()} deleted successfully'})
        else:
            return jsonify({'success': False, 'error': f'Failed to delete {category}'})

    except Exception as e:
        print('Exception:', str(e))
        return jsonify({'success': False, 'error': 'Invalid data format'})


@main_routes.route('/report/<category>')
def download_csv(category):
    if not session.get('logged_in'):
        return redirect(url_for('login'))

    columns, devices = get_category_data(category)

    csv_data = ','.join([column_mapping.get(column, column) for column in columns[1:]]) + '\n'
    csv_data += '\n'.join([','.join(map(str, device[1:])) for device in devices])

    response = Response(csv_data, mimetype='text/csv')
    response.headers['Content-Disposition'] = f'attachment; filename={category}_report.csv'

    return response

templates/dashboard.html
<!DOCTYPE html>
<html>
<head>
    <title>Dashboard</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link rel="stylesheet" href={{ url_for('static', filename='css/dashboard.css') }}>
</head>
<body>
  <div class="top-bar">
    <!-- Logo -->
    <a href="/dashboard"><img id="logo" src="{{ url_for('static', filename='img/logo-full.png') }}" alt="Logo"></a>

    <!-- Top Right Buttons -->
    <div id="topRightButtons" class="button-container">
      <!-- Report -->
      <!--
      <button id="reportButton" class="top-right-button"><strong>REPORT</strong></button>
      <span class="separator"></span>
      -->

      {% if is_admin %}
        <!-- Manage Users -->
        <button id="manageUsersButton" class="top-right-button"><strong>MANAGE USERS</strong></button>
        <span class="separator"></span>
      {% endif %}

      <!-- Logout -->
      <a href="{{ url_for('auth.logout') }}"><img id="logoutIcon" src="{{ url_for('static', filename='img/icon-logout-blue.svg') }}" alt="Logout" onclick="logout()"></a>
    </div>
  </div>

  <div class="ribbon">
    <!-- Ribbon Title -->
    <p id="ribbonTitle" class="ribbon-title">
      <strong>{% if is_admin %}Admin Dashboard{% else %}Dashboard{% endif %}</strong>
    </p>
  </div>

  <!-- Table for Categories -->
  <div class="dashboard-container">
    <div class="categories-table">
        <h3>Categories</h3>
        <div id="categoryButtons" class="category-buttons-container">
          {% for category in categories %}
            <a href="{{ url_for('main.segmentation', category=category) }}">
              <hr>
              <button class="category-button">{{ column_mapping.get(category, category) }}</button>
            </a>
          {% endfor %}
        </div>
    </div>
    <div class="chart-container">
      <div id="chart-container"></div>
    </div>
  </div>

  <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
  <script src="{{ url_for('static', filename='js/totalCountChart.js') }}"></script>
  <script src="{{ url_for('static', filename='js/timeout.js') }}"></script>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
    <link rel="stylesheet" href={{ url_for('static', filename='css/login.css') }}>
</head>
<body>
  <div class="logo-container">
    <img src="{{ url_for('static', filename='img/logo-full.png') }}" alt="Logo">
  </div>

  <div class="ribbon"></div>

  <div class="black-box">
    <div class="title">
      <h1>GTL Library Management System</h1>
    </div>
    <div class="login-container">
      <img id="avatarIcon" src="{{ url_for('static', filename='img/icon-avatar-blue.svg') }}" alt="Avatar">
      <form method="post" action="/login">
        <input type="text" id="username" name="username" placeholder="Username" required><br><br>
        <input type="password" id="password" name="password" placeholder="Password" required><br><br>
        <input type="submit" value="LOGIN">
      </form>
    </div>
  </div>
</body>
</html>

templates/segmentation.html
<!DOCTYPE html>
<html>
<head>
    <title>Segmentation - {{ table_name }}</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link rel="stylesheet" href={{ url_for('static', filename='css/segmentation.css') }}>
</head>
<body>
  <div class="top-bar">
    <!-- Logo -->
    <a href="/dashboard"><img id="logo" src="{{ url_for('static', filename='img/logo-full.png') }}" alt="Logo"></a>

    <!-- Top Right Buttons -->
    <div id="topRightButtons" class="button-container">
      {% if is_admin %}
        <!-- Add Device Button -->
        <button id="addDeviceButton" class="top-right-button"><strong>ADD DEVICE</strong></button>
        <span class="separator"></span>

        <!-- Edit Device -->
        <button id="editDeviceButton" class="top-right-button"><strong>EDIT DEVICE</strong></button>
        <span class="separator"></span>

        <!-- Manage Users -->
        <button id="manageUsersButton" class="top-right-button"><strong>MANAGE USERS</strong></button>
        <span class="separator"></span>
      {% endif %}

      <form action="{{ url_for('main.download_csv', category=category) }}" method="get">
        <button type="submit" id="reportButton" class="top-right-button"><strong>REPORT</strong></button>
        <span class="separator"></span>
      </form>

      <!-- Search Bar -->
      <input type="text" id="searchInput" class="search-bar" placeholder="Search by Device Name, SNID, Tag, Model, User, IP Address, or Mobile Number">
      <img id="searchIcon" src="{{ url_for('static', filename='img/icon-search-blue.svg') }}" alt="Search">
      <span class="separator"></span>

      <!-- Logout -->
      <a href="{{ url_for('auth.logout') }}"><img id="logoutIcon" src="{{ url_for('static', filename='img/icon-logout-blue.svg') }}" alt="Logout" onclick="logout()"></a>
    </div>
  </div>

  <!-- Add Device Popup -->
  <div id="addDevicePopup" class="modal">
    <div class="modal-content">
      <span id="closeAddDevicePopup" class="close">&times;</span>
      <h2>Add Device Information</h2>
      <form id="addDeviceForm" action="/add_device" method="POST">
        <button type="submit">Add Device</button>
      </form>
    </div>
  </div>

  <!-- Edit Device Popup -->
  <div id="deviceInfoPopup" class="modal">
    <div class="modal-content">
      <span id="closeDeviceInfoPopup" class="close">&times;</span>
      <h2>Edit Device Information</h2>
      <form id="editDeviceForm">
        <button type="submit" id="saveChangesButton">Save Changes</button>
        <button type="button" id="deleteDeviceButton">Delete Device</button>
      </form>
    </div>
  </div>

  <!-- Ribbon Section -->
  <div class="ribbon">
    <!-- Ribbon Title -->
    <p id="ribbonTitle" class="ribbon-title">
      <strong>{% if is_admin %}Admin Dashboard{% else %}Dashboard{% endif %}</strong>
      <span class="separator">
        <strong>|</strong>
      </span>
      {{ table_name }}
    </p>
    <!-- Dashboard Button -->
    <a href="/dashboard" id="categoryButton" class="ribbon-button">
      <strong>Categories</strong>
    </a>
  </div>

  <!-- Table -->
  <table>
    <thead>
      <tr>
        {% for column in columns %}
          <th>{{ column_mapping.get(column, column) }}</th>
        {% endfor %}
      </tr>
    </thead>
    <tbody>
      {% for device in devices %}
        <tr data-device-id="{{ device[0] }}">
          {% for value in device %}
            <td>{{ value }}</td>
          {% endfor %}
        </tr>
      {% endfor %}
    </tbody>
  </table>

  <p id="noResultsMessage">No results found</p>

  <script src="{{ url_for('static', filename='js/addDevice.js') }}"></script>
  <script src="{{ url_for('static', filename='js/editDevice.js') }}"></script>
  <script src="{{ url_for('static', filename='js/search.js') }}"></script>
  <script src="{{ url_for('static', filename='js/timeout.js') }}"></script>
</body>
</html>

templates/timeout.html
<!DOCTYPE html>
<html>
<head>
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/timeout.css') }}">
</head>
<body>
  <div class="logo-container">
    <img src="{{ url_for('static', filename='img/logo-full.png') }}" alt="Logo">
  </div>

  <div class="ribbon"></div>

  <div class="message-container">
    <p class="session-timeout">Your session has timed out.</p>
    <p class="login-again"><a class="login-link" href="{{ url_for('auth.index') }}">Click here</a> to log in again.</p>
  </div>
</body>
</html>